name: CI Pruebas Unitarias

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Configurar PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Mostrar estructura
        run: |
          pwd
          ls -R
      - name: Ejecutar pruebas
        run: |
          python -c "import os; print(os.getcwd())"
          python -c "import sys; print(sys.path)"
          python -m pytest --cov=app --cov-fail-under=80